#!/bin/bash

# Install necessary python packages
pip install paho-mqtt playsound

# Update PI ID
read -p "Enter PI ID (integer): " num
while ! [[ "$number" =~ ^[0-9]+$ ]]; do
    echo "Invalid input. Please enter a number."
    read -p "Enter  PI ID (integer): " num
done

echo "Setting PI_ID of: $num"
echo "export PI_ID=\"$num\"" >> ~/.bashrc
source ~/.bashrc